# Generated by Django 4.1.3 on 2022-12-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_image', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
